version: "3.3"
services:
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
  postgres:
    container_name: postgres
    image: postgres.db
    build:
      context: ./
      dockerfile: postgres.Dockerfile
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq.management
    build:
      context: ./
      dockerfile: rabbit.Dockerfile
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"