spring:
  r2dbc:
    url: r2dbc:pool:postgresql://localhost:5432/tenpo
    username: postgres
    password: postgres
  data:
    redis:
      host: localhost
      port: 6379
      ttl: 1
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    queueName: requestLog